### ISSUE TITLE
No trigger success/error at model change

### ISSUE THREAD

**Issue by ollivierv** [8bitDesigner/ng-form-group#2]
Hi,
If model bound variable is modified, the view state doesn't change. 
Is there a easy way to acheive this ? 
Thx,

**Comment by 8bitDesigner** [comment]
Sure, but there are two "gotchas". First, no state changes are applied to `$pristine` form elements. This is so that in our use case, you don't end up with a list of red "invalid" form fields when you load the page.

Second, you have to trigger an Angular `$digest` in order for the state change to be picked up. The easiest way to do this is use `$scope.$apply` to change your model bound variable inside: `$scope.$apply("userEmailAddress = 'paul@example.com'")`

Here's a Plunker example:  http://plnkr.co/edit/E2ihEyGKZJBkrBfeU1iP?p=preview

I've just added a tiny directive to auto-dirty its attached form element:

``` html
<input dirtify ng-model="myEmailModel">
```

``` javascript
angular.module('myApp').directive('dirtify', function() {
  return {
      require: "ngModel",
      link: function(scope, el, attrs, ngModel) { ngModel.$setDirty() }
  }
})
```

This pulls in the `ngModel` controller and "dirties" the input on boot, causing the input state to turn red, because it's a required field and it has no input. Then, after 1500ms, the controller runs this code:

``` javascript
angular.module('myApp').controller('TestController', function($scope, $timeout) {
  $timeout(function() {
    $scope.$apply('myEmailModel = "test@email.com"')
  }, 1500)
})
```

To apply a valid email into that model, causing the form to revalidate and turn green :)

Hope that helps you out. Long term, if this is a common case, I can see adding a `ng-form-group-options` attribute, so you can configure the directive to ignore the dirty check by saying:  `ng-form-group-options="{requireDirty: false}"`

**Comment by ollivierv** [comment]
Thanks a lot. The directive('dirtify') do the job perfectly !
